"""实验室平台增量结构

Revision ID: 0002_platform
Revises: 0001_legacy_baseline
Create Date: 2026-09-21 14:15:07.695992
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.db


revision: str = '0002_platform'
down_revision: Union[str, None] = '0001_legacy_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('subject_kind', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('step_advances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('from_step_id', sa.String(), nullable=False),
    sa.Column('from_attempt', sa.Integer(), nullable=False),
    sa.Column('to_step_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'from_step_id', 'from_attempt', name='uq_step_advance')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('asset_no', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('serial', sa.String(), nullable=False),
    sa.Column('lab_id', sa.String(), nullable=False),
    sa.Column('owner_person_id', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('calibration_applicable', sa.Boolean(), nullable=False),
    sa.Column('calibration_exempt_reason', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'asset_no', name='uq_asset_org_no')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_org_id'), ['org_id'], unique=False)

    op.create_table('experiment_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('plan_version_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('assignee_user_id', sa.String(), nullable=False),
    sa.Column('reviewer_user_id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('sample_ids', sa.JSON(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('experiment_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiment_tasks_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiment_tasks_org_id'), ['org_id'], unique=False)
        # 部分唯一索引：未绑定批次的任务（batch_id = ''）不互相冲突
        batch_op.create_index(
            'uq_task_batch', ['batch_id'], unique=True,
            postgresql_where=sa.text("batch_id <> ''"),
        )
        batch_op.create_index(batch_op.f('ix_experiment_tasks_plan_id'), ['plan_id'], unique=False)

    op.create_table('file_objects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('ref_type', sa.String(), nullable=False),
    sa.Column('ref_id', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('file_objects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_objects_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_file_ref', ['ref_type', 'ref_id'], unique=False)

    op.create_table('ingest_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('service_identity_id', sa.String(), nullable=False),
    sa.Column('analysis_task_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('digest', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'source', 'analysis_task_id', 'event_id', name='uq_ingest_event')
    )
    with op.batch_alter_table('ingest_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingest_events_org_id'), ['org_id'], unique=False)

    op.create_table('inventory_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('step_run_id', sa.String(), nullable=False),
    sa.Column('command_id', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reverses_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'source', 'event_id', name='uq_inventory_event')
    )
    with op.batch_alter_table('inventory_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_events_org_id'), ['org_id'], unique=False)

    op.create_table('labs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labs_org_id'), ['org_id'], unique=False)

    op.create_table('materials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_unit', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('cas', sa.String(), nullable=False),
    sa.Column('conversions', sa.JSON(), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=False),
    sa.Column('ghs', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'code', name='uq_material_org_code')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_org_id'), ['org_id'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('default_lab_id', sa.String(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_membership_org_user')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('metric_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('value_type', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('method_version', sa.String(), nullable=False),
    sa.Column('sample_types', sa.JSON(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'code', 'version', name='uq_metric_code_version')
    )
    with op.batch_alter_table('metric_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_definitions_org_id'), ['org_id'], unique=False)

    op.create_table('people',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lab_id', sa.String(), nullable=False),
    sa.Column('employment_state', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'code', name='uq_person_org_code')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_org_id'), ['org_id'], unique=False)

    op.create_table('physical_samples',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('sample_type', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('quantity', app.core.db.Quantity(precision=18, scale=6), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('storage_condition', sa.String(), nullable=False),
    sa.Column('current_location', sa.String(), nullable=False),
    sa.Column('location_note', sa.String(), nullable=False),
    sa.Column('custodian', sa.String(), nullable=False),
    sa.Column('lifecycle_state', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['physical_samples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'barcode', name='uq_sample_org_barcode')
    )
    with op.batch_alter_table('physical_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_physical_samples_org_id'), ['org_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('restricted', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'code', name='uq_project_org_code')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_org_id'), ['org_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'code', name='uq_report_org_code')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_org_id'), ['org_id'], unique=False)

    op.create_table('resource_bookings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('station_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('step_run_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_bookings_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_bookings_org_id'), ['org_id'], unique=False)

    op.create_table('service_identities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('secret_hash', sa.String(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('rotated_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'source', name='uq_service_identity_source')
    )
    with op.batch_alter_table('service_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_identities_org_id'), ['org_id'], unique=False)

    op.create_table('sops',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'code', name='uq_sop_org_code')
    )
    with op.batch_alter_table('sops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sops_org_id'), ['org_id'], unique=False)

    op.create_table('workflow_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('step_run_id', sa.String(), nullable=False),
    sa.Column('event_key', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_by', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'event_key', name='uq_workflow_event_key')
    )
    with op.batch_alter_table('workflow_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_events_org_id'), ['org_id'], unique=False)

    op.create_table('calibration_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('capability_scope', sa.JSON(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('certificate_file_id', sa.String(), nullable=False),
    sa.Column('registered_by', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calibration_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calibration_records_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_records_org_id'), ['org_id'], unique=False)

    op.create_table('inventory_ledger',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('event_row_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('lot_id', sa.String(), nullable=False),
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('step_run_id', sa.String(), nullable=False),
    sa.Column('quantity', app.core.db.Quantity(precision=18, scale=6), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('balance_delta', app.core.db.Quantity(precision=18, scale=6), nullable=False),
    sa.Column('balance_after', app.core.db.Quantity(precision=18, scale=6), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_row_id'], ['inventory_events.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'source', 'event_id', 'line_no', name='uq_ledger_event_line')
    )
    with op.batch_alter_table('inventory_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_ledger_event_row_id'), ['event_row_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_ledger_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_ledger_org_id'), ['org_id'], unique=False)

    op.create_table('plan_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('approver_id', sa.String(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('signature_id', sa.String(), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'version', name='uq_plan_version')
    )
    with op.batch_alter_table('plan_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_versions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_versions_plan_id'), ['plan_id'], unique=False)

    op.create_table('project_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member')
    )
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_members_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_members_user_id'), ['user_id'], unique=False)

    op.create_table('qualifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('scope_kind', sa.String(), nullable=False),
    sa.Column('scope_ref', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('evidence_file_id', sa.String(), nullable=False),
    sa.Column('granted_by', sa.String(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qualifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qualifications_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qualifications_person_id'), ['person_id'], unique=False)

    op.create_table('report_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('template_version', sa.String(), nullable=False),
    sa.Column('algorithm_version', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('approver_id', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('publish_snapshot', sa.JSON(), nullable=False),
    sa.Column('pdf_file_id', sa.String(), nullable=False),
    sa.Column('signature_id', sa.String(), nullable=False),
    sa.Column('supersedes_id', sa.String(), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'version', name='uq_report_version')
    )
    with op.batch_alter_table('report_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_versions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_versions_report_id'), ['report_id'], unique=False)

    op.create_table('result_values',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('analysis_task_id', sa.String(), nullable=False),
    sa.Column('physical_sample_id', sa.String(), nullable=False),
    sa.Column('assignment_id', sa.String(), nullable=False),
    sa.Column('metric_definition_id', sa.String(), nullable=False),
    sa.Column('ingest_event_id', sa.String(), nullable=False),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('raw_file_id', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=False),
    sa.Column('parser_version', sa.String(), nullable=False),
    sa.Column('result_version', sa.Integer(), nullable=False),
    sa.Column('revises_id', sa.String(), nullable=False),
    sa.Column('superseded_by_id', sa.String(), nullable=False),
    sa.Column('not_measured_reason', sa.Text(), nullable=False),
    sa.Column('quality', sa.String(), nullable=False),
    sa.Column('review_state', sa.String(), nullable=False),
    sa.Column('provenance', sa.String(), nullable=False),
    sa.Column('entered_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['metric_definition_id'], ['metric_definitions.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_task_id', 'metric_definition_id', 'result_version', name='uq_result_version')
    )
    with op.batch_alter_table('result_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_result_values_analysis_task_id'), ['analysis_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_result_values_org_id'), ['org_id'], unique=False)

    op.create_table('sample_transfers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('physical_sample_id', sa.String(), nullable=False),
    sa.Column('event_key', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('from_location', sa.String(), nullable=False),
    sa.Column('to_location', sa.String(), nullable=False),
    sa.Column('from_party', sa.String(), nullable=False),
    sa.Column('to_party', sa.String(), nullable=False),
    sa.Column('quantity', app.core.db.Quantity(precision=18, scale=6), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('confirm_method', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['physical_sample_id'], ['physical_samples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'physical_sample_id', 'event_key', name='uq_transfer_event')
    )
    with op.batch_alter_table('sample_transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sample_transfers_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_transfers_physical_sample_id'), ['physical_sample_id'], unique=False)

    op.create_table('slot_occupancies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('container_id', sa.String(), nullable=False),
    sa.Column('well', sa.String(), nullable=False),
    sa.Column('physical_sample_id', sa.String(), nullable=False),
    sa.Column('assignment_id', sa.String(), nullable=False),
    sa.Column('occupied_at', sa.DateTime(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['physical_sample_id'], ['physical_samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slot_occupancies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slot_occupancies_org_id'), ['org_id'], unique=False)
        # 只约束在途占用；已释放的历史记录可以有很多条
        batch_op.create_index(
            'uq_slot_live', ['container_id', 'well'], unique=True,
            postgresql_where=sa.text('released_at IS NULL'),
        )

    op.create_table('sop_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('sop_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_checksum', sa.String(), nullable=False),
    sa.Column('capability_scope', sa.JSON(), nullable=False),
    sa.Column('sample_types', sa.JSON(), nullable=False),
    sa.Column('requires_training_ack', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('approver_id', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['sop_id'], ['sops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sop_id', 'version', name='uq_sop_version')
    )
    with op.batch_alter_table('sop_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sop_versions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sop_versions_sop_id'), ['sop_id'], unique=False)

    op.create_table('task_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('from_user_id', sa.String(), nullable=False),
    sa.Column('to_user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['experiment_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_assignments_task_id'), ['task_id'], unique=False)

    op.create_table('result_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('result_value_id', sa.String(), nullable=False),
    sa.Column('result_version', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('conclusion', sa.String(), nullable=False),
    sa.Column('quality', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('signature_id', sa.String(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['result_value_id'], ['result_values.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('result_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_result_reviews_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_result_reviews_result_value_id'), ['result_value_id'], unique=False)

    op.create_table('sop_acks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sop_version_id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('acked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sop_version_id'], ['sop_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sop_version_id', 'person_id', name='uq_sop_ack')
    )
    with op.batch_alter_table('sop_acks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sop_acks_sop_version_id'), ['sop_version_id'], unique=False)

    op.create_table('step_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('step_id', sa.String(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('step_snapshot', sa.JSON(), nullable=False),
    sa.Column('assignee_user_id', sa.String(), nullable=False),
    sa.Column('station_id', sa.String(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('form_data', sa.JSON(), nullable=False),
    sa.Column('conclusion', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('submitted_by', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'step_id', 'attempt', name='uq_step_run_attempt')
    )
    with op.batch_alter_table('step_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_runs_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_runs_org_id'), ['org_id'], unique=False)

    # ---------- 已有表的增量 ----------
    # 新列一律带 server_default：老库里已有行，不带默认值的 NOT NULL 加列会失败。
    # 默认值只保证迁移能过，业务含义由 0003 的数据迁移与责任人确认填写。

    with op.batch_alter_table("adapters", schema=None) as batch_op:
        batch_op.add_column(sa.Column("kind", sa.String(), nullable=False, server_default="simulation"))
        batch_op.add_column(sa.Column("supports_hold", sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column("supports_abort", sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column("supports_query", sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column("supports_dedup", sa.Boolean(), nullable=False, server_default=sa.true()))

    with op.batch_alter_table("alarms", schema=None) as batch_op:
        batch_op.add_column(sa.Column("org_id", sa.String(), nullable=False, server_default=""))
        batch_op.create_index(batch_op.f("ix_alarms_org_id"), ["org_id"], unique=False)

    with op.batch_alter_table("allocations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("asset_id", sa.String(), nullable=False, server_default=""))

    with op.batch_alter_table("analysis_tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("org_id", sa.String(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column("physical_sample_id", sa.String(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column("method_version", sa.String(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column("required_metrics", sa.JSON(), nullable=False, server_default="[]"))
        batch_op.add_column(sa.Column("round_no", sa.Integer(), nullable=False, server_default="1"))
        batch_op.add_column(sa.Column("retest_of", sa.String(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column("created_by", sa.String(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column("row_version", sa.Integer(), nullable=False, server_default="1"))
        batch_op.create_index(batch_op.f("ix_analysis_tasks_org_id"), ["org_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_analysis_tasks_physical_sample_id"), ["physical_sample_id"], unique=False
        )

    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("org_id", sa.String(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column("user_id", sa.String(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column("object_version", sa.Integer(), nullable=False, server_default="0"))
        batch_op.create_index(batch_op.f("ix_audit_events_org_id"), ["org_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_target"), ["target"], unique=False)

    with op.batch_alter_table("batches", schema=None) as batch_op:
        batch_op.add_column(sa.Column("org_id", sa.String(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column("plan_version", sa.Integer(), nullable=False, server_default="1"))
        batch_op.add_column(sa.Column("task_id", sa.String(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column("sop_snapshot", sa.JSON(), nullable=False, server_default="{}"))
        batch_op.add_column(sa.Column("row_version", sa.Integer(), nullable=False, server_default="1"))
        batch_op.create_index(batch_op.f("ix_batches_org_id"), ["org_id"], unique=False)

    with op.batch_alter_table("checkpoints", schema=None) as batch_op:
        batch_op.add_column(sa.Column("step_run_id", sa.String(), nullable=False, server_default=""))

    with op.batch_alter_table("commands", schema=None) as batch_op:
        batch_op.add_column(sa.Column("org_id", sa.String(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column("step_run_id", sa.String(), nullable=False, server_default=""))
        # 历史指令都已到终态，投递状态按「已确认」迁移；未知态由 0003 单独处理
        batch_op.add_column(
            sa.Column("delivery_state", sa.String(), nullable=False, server_default="delivered")
        )
        batch_op.create_index(batch_op.f("ix_commands_org_id"), ["org_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_commands_step_run_id"), ["step_run_id"], unique=False)

    with op.batch_alter_table("esignatures", schema=None) as batch_op:
        batch_op.add_column(sa.Column("object_ref", sa.String(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column("object_version", sa.Integer(), nullable=False, server_default="0"))

    # 幂等记录的主键从 key 改成代理键，作用域唯一约束换成 (org, subject, action, key)。
    # 这些行是短生命周期的请求去重记录，重建比原地改主键干净。
    op.drop_table("idempotency_keys")
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False, server_default=""),
        sa.Column("subject", sa.String(), nullable=False, server_default=""),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("request_digest", sa.String(), nullable=False, server_default=""),
        sa.Column("status", sa.Integer(), nullable=False, server_default="200"),
        sa.Column("body", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "subject", "action", "key", name="uq_idempotency_scope"),
    )

    with op.batch_alter_table("lots", schema=None) as batch_op:
        batch_op.add_column(sa.Column("org_id", sa.String(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column("material_id", sa.String(), nullable=False, server_default=""))
        batch_op.add_column(
            sa.Column(
                "opening_balance", app.core.db.Quantity(precision=18, scale=6),
                nullable=False, server_default="0",
            )
        )
        batch_op.add_column(sa.Column("open_expiry", sa.String(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column("open_expiry_basis", sa.String(), nullable=False, server_default=""))
        batch_op.alter_column(
            "qty", existing_type=sa.FLOAT(),
            type_=app.core.db.Quantity(precision=18, scale=6), existing_nullable=False,
        )
        batch_op.create_index(batch_op.f("ix_lots_org_id"), ["org_id"], unique=False)

    with op.batch_alter_table("plans", schema=None) as batch_op:
        batch_op.add_column(sa.Column("org_id", sa.String(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column("project_id", sa.String(), nullable=False, server_default=""))
        # 旧「已锁定」不自动视为已审批：审批状态一律从 draft 起算
        batch_op.add_column(sa.Column("approval_state", sa.String(), nullable=False, server_default="draft"))
        batch_op.add_column(sa.Column("plan_type", sa.String(), nullable=False, server_default="matrix"))
        batch_op.add_column(sa.Column("version", sa.Integer(), nullable=False, server_default="1"))
        batch_op.add_column(sa.Column("sample_count", sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("sample_ids", sa.JSON(), nullable=False, server_default="[]"))
        batch_op.add_column(sa.Column("required_metrics", sa.JSON(), nullable=False, server_default="[]"))
        batch_op.add_column(
            sa.Column("resource_requirements", sa.JSON(), nullable=False, server_default="[]")
        )
        batch_op.add_column(sa.Column("method_version", sa.String(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column("reject_reason", sa.Text(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column("row_version", sa.Integer(), nullable=False, server_default="1"))
        batch_op.create_index(batch_op.f("ix_plans_org_id"), ["org_id"], unique=False)

    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("org_id", sa.String(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column("sop_version_id", sa.String(), nullable=False, server_default=""))
        batch_op.create_index(batch_op.f("ix_recipes_org_id"), ["org_id"], unique=False)

    with op.batch_alter_table("reservations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("org_id", sa.String(), nullable=False, server_default=""))
        for column in ("consumed_qty", "loss_qty", "released_qty", "issued_qty", "returned_qty"):
            batch_op.add_column(
                sa.Column(
                    column, app.core.db.Quantity(precision=18, scale=6),
                    nullable=False, server_default="0",
                )
            )
        batch_op.add_column(
            sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now())
        )
        batch_op.add_column(sa.Column("row_version", sa.Integer(), nullable=False, server_default="1"))
        batch_op.alter_column(
            "qty", existing_type=sa.FLOAT(),
            type_=app.core.db.Quantity(precision=18, scale=6), existing_nullable=False,
        )
        batch_op.create_index(batch_op.f("ix_reservations_batch_id"), ["batch_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_reservations_org_id"), ["org_id"], unique=False)

    with op.batch_alter_table("results", schema=None) as batch_op:
        batch_op.add_column(sa.Column("org_id", sa.String(), nullable=False, server_default=""))
        batch_op.create_index(batch_op.f("ix_results_org_id"), ["org_id"], unique=False)

    with op.batch_alter_table("samples", schema=None) as batch_op:
        batch_op.add_column(sa.Column("org_id", sa.String(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column("physical_sample_id", sa.String(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column("container_id", sa.String(), nullable=False, server_default=""))
        batch_op.create_index(batch_op.f("ix_samples_org_id"), ["org_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_samples_physical_sample_id"), ["physical_sample_id"], unique=False
        )

    with op.batch_alter_table("stations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("org_id", sa.String(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column("asset_id", sa.String(), nullable=False, server_default=""))
        batch_op.create_index(batch_op.f("ix_stations_org_id"), ["org_id"], unique=False)

    with op.batch_alter_table("telemetry", schema=None) as batch_op:
        # 历史遥测是模拟序列，来源标签如实写 simulation，不冒充真实采集
        batch_op.add_column(sa.Column("origin", sa.String(), nullable=False, server_default="simulation"))

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("state", sa.String(), nullable=False, server_default="active"))

    with op.batch_alter_table("waste_tanks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("org_id", sa.String(), nullable=False, server_default=""))
        batch_op.create_index(batch_op.f("ix_waste_tanks_org_id"), ["org_id"], unique=False)


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waste_tanks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waste_tanks_org_id'))
        batch_op.drop_column('org_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('state')

    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.drop_column('origin')

    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stations_org_id'))
        batch_op.drop_column('asset_id')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_samples_physical_sample_id'))
        batch_op.drop_index(batch_op.f('ix_samples_org_id'))
        batch_op.drop_column('container_id')
        batch_op.drop_column('physical_sample_id')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_results_org_id'))
        batch_op.drop_column('org_id')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservations_org_id'))
        batch_op.drop_index(batch_op.f('ix_reservations_batch_id'))
        batch_op.alter_column('qty',
               existing_type=app.core.db.Quantity(precision=18, scale=6),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('row_version')
        batch_op.drop_column('created_at')
        batch_op.drop_column('returned_qty')
        batch_op.drop_column('issued_qty')
        batch_op.drop_column('released_qty')
        batch_op.drop_column('loss_qty')
        batch_op.drop_column('consumed_qty')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_org_id'))
        batch_op.drop_column('sop_version_id')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_org_id'))
        batch_op.drop_column('row_version')
        batch_op.drop_column('reject_reason')
        batch_op.drop_column('method_version')
        batch_op.drop_column('resource_requirements')
        batch_op.drop_column('required_metrics')
        batch_op.drop_column('sample_ids')
        batch_op.drop_column('sample_count')
        batch_op.drop_column('version')
        batch_op.drop_column('plan_type')
        batch_op.drop_column('approval_state')
        batch_op.drop_column('project_id')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lots_org_id'))
        batch_op.alter_column('qty',
               existing_type=app.core.db.Quantity(precision=18, scale=6),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('open_expiry_basis')
        batch_op.drop_column('open_expiry')
        batch_op.drop_column('opening_balance')
        batch_op.drop_column('material_id')
        batch_op.drop_column('org_id')

    op.drop_table("idempotency_keys")
    op.create_table(
        "idempotency_keys",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("body", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )

    with op.batch_alter_table('esignatures', schema=None) as batch_op:
        batch_op.drop_column('object_version')
        batch_op.drop_column('object_ref')

    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commands_step_run_id'))
        batch_op.drop_index(batch_op.f('ix_commands_org_id'))
        batch_op.drop_column('delivery_state')
        batch_op.drop_column('step_run_id')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('checkpoints', schema=None) as batch_op:
        batch_op.drop_column('step_run_id')

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_org_id'))
        batch_op.drop_column('row_version')
        batch_op.drop_column('sop_snapshot')
        batch_op.drop_column('task_id')
        batch_op.drop_column('plan_version')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_target'))
        batch_op.drop_index(batch_op.f('ix_audit_events_org_id'))
        batch_op.drop_column('object_version')
        batch_op.drop_column('user_id')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('analysis_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_tasks_physical_sample_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_tasks_org_id'))
        batch_op.drop_column('row_version')
        batch_op.drop_column('created_by')
        batch_op.drop_column('retest_of')
        batch_op.drop_column('round_no')
        batch_op.drop_column('required_metrics')
        batch_op.drop_column('method_version')
        batch_op.drop_column('physical_sample_id')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('allocations', schema=None) as batch_op:
        batch_op.drop_column('asset_id')

    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alarms_org_id'))
        batch_op.drop_column('org_id')

    with op.batch_alter_table('adapters', schema=None) as batch_op:
        batch_op.drop_column('supports_dedup')
        batch_op.drop_column('supports_query')
        batch_op.drop_column('supports_abort')
        batch_op.drop_column('supports_hold')
        batch_op.drop_column('kind')

    with op.batch_alter_table('step_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_runs_org_id'))
        batch_op.drop_index(batch_op.f('ix_step_runs_batch_id'))

    op.drop_table('step_runs')
    with op.batch_alter_table('sop_acks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sop_acks_sop_version_id'))

    op.drop_table('sop_acks')
    with op.batch_alter_table('result_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_result_reviews_result_value_id'))
        batch_op.drop_index(batch_op.f('ix_result_reviews_org_id'))

    op.drop_table('result_reviews')
    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_assignments_task_id'))

    op.drop_table('task_assignments')
    with op.batch_alter_table('sop_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sop_versions_sop_id'))
        batch_op.drop_index(batch_op.f('ix_sop_versions_org_id'))

    op.drop_table('sop_versions')
    with op.batch_alter_table('slot_occupancies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slot_occupancies_org_id'))

    op.drop_table('slot_occupancies')
    with op.batch_alter_table('sample_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sample_transfers_physical_sample_id'))
        batch_op.drop_index(batch_op.f('ix_sample_transfers_org_id'))

    op.drop_table('sample_transfers')
    with op.batch_alter_table('result_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_result_values_org_id'))
        batch_op.drop_index(batch_op.f('ix_result_values_analysis_task_id'))

    op.drop_table('result_values')
    with op.batch_alter_table('report_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_versions_report_id'))
        batch_op.drop_index(batch_op.f('ix_report_versions_org_id'))

    op.drop_table('report_versions')
    with op.batch_alter_table('qualifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qualifications_person_id'))
        batch_op.drop_index(batch_op.f('ix_qualifications_org_id'))

    op.drop_table('qualifications')
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_members_project_id'))

    op.drop_table('project_members')
    with op.batch_alter_table('plan_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_versions_plan_id'))
        batch_op.drop_index(batch_op.f('ix_plan_versions_org_id'))

    op.drop_table('plan_versions')
    with op.batch_alter_table('inventory_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_ledger_org_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_ledger_lot_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_ledger_event_row_id'))

    op.drop_table('inventory_ledger')
    with op.batch_alter_table('calibration_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calibration_records_org_id'))
        batch_op.drop_index(batch_op.f('ix_calibration_records_asset_id'))

    op.drop_table('calibration_records')
    with op.batch_alter_table('workflow_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_events_org_id'))

    op.drop_table('workflow_events')
    with op.batch_alter_table('sops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sops_org_id'))

    op.drop_table('sops')
    with op.batch_alter_table('service_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_identities_org_id'))

    op.drop_table('service_identities')
    with op.batch_alter_table('resource_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_bookings_org_id'))
        batch_op.drop_index(batch_op.f('ix_resource_bookings_asset_id'))

    op.drop_table('resource_bookings')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_org_id'))

    op.drop_table('reports')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_org_id'))

    op.drop_table('projects')
    with op.batch_alter_table('physical_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_physical_samples_org_id'))

    op.drop_table('physical_samples')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_org_id'))

    op.drop_table('people')
    with op.batch_alter_table('metric_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_definitions_org_id'))

    op.drop_table('metric_definitions')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_org_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_org_id'))

    op.drop_table('materials')
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labs_org_id'))

    op.drop_table('labs')
    with op.batch_alter_table('inventory_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_events_org_id'))

    op.drop_table('inventory_events')
    with op.batch_alter_table('ingest_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingest_events_org_id'))

    op.drop_table('ingest_events')
    with op.batch_alter_table('file_objects', schema=None) as batch_op:
        batch_op.drop_index('ix_file_ref')
        batch_op.drop_index(batch_op.f('ix_file_objects_org_id'))

    op.drop_table('file_objects')
    with op.batch_alter_table('experiment_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiment_tasks_plan_id'))
        batch_op.drop_index(batch_op.f('ix_experiment_tasks_org_id'))
        batch_op.drop_index(batch_op.f('ix_experiment_tasks_batch_id'))

    op.drop_table('experiment_tasks')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_org_id'))

    op.drop_table('assets')
    op.drop_table('step_advances')
    op.drop_table('organizations')
    op.drop_table('access_logs')
    # ### end Alembic commands ###
