from . import (
    admin, alarms, analysis, assets, auth, batches, comments, environment, exceptions, files, governance,
    integrations, labware, maintenance,
    materials, methods,
    metrics,
    people,
    plans, recipes, report_templates, reports, results, runtime, samples, schedule, sops, stations, steps, stream, tasks,
    templates,
)

ROUTERS = [
    auth.router,
    admin.router,
    governance.router,
    people.router,
    assets.router,
    maintenance.router,
    recipes.router,
    methods.router,
    comments.router,
    environment.router,
    plans.router,
    tasks.router,
    batches.router,
    steps.router,
    schedule.router,
    stations.router,
    templates.router,
    runtime.router,
    materials.router,
    samples.router,
    metrics.router,
    analysis.router,
    alarms.router,
    results.router,
    sops.router,
    reports.router,
    report_templates.router,
    files.router,
    stream.router,
    labware.router,
    exceptions.router,
    integrations.router,
]
